import { getDefaultNormalizer } from "@testing-library/react"

export const items = [
  {
    id: "1",
    name: "Coffee Cup 2dl",
    price: "8€",
    image: "/images/Coffee Cup 2dl.png",
    customerName:'Richard',
    phone:'0449351234',
    email:'richard@gmail.com',
    category:'Home accessories',
    description:
      "The Oiva coffee cup is made of white ceramic that is machine washable, oven, microwave and freezer resistant. The cup has a brick pattern made with relief technology. The brick pattern was designed by Marimekko's founder Armi Ratia. It reflects her belief in the simple beauty of everyday life. Please remove the product label on the bottom of the containers before use. The sticker contains metal.",
  },
  {
    id: "2",
    name: "Plate 15x12cm",
    price: "30€",
    image: "./images/Plate 15x12cm.png",
    customerName:'Oliver',
    phone:'0449353232',
    email:'Oliver@gmail.com',
    category:'Home accessories',
    description:
      "The small rectangular Oiva plate is made of white ceramic that is machine washable, oven, microwave and freezing resistant. The plate has a brick pattern made with relief technology. The brick pattern was designed by Marimekko's founder Armi Ratia. It reflects her belief in the simple beauty of everyday life. Please remove the product label on the bottom of the containers before use. The sticker contains metal.",
  },
  {
    id: "3",
    name: "Karla Chain Bag",
    price: "220€",
    image: "./images/Karla Chain Bag.png",
    customerName:'Charles',
    phone:'0449351234',
    email:'Charles@gmail.com',
    category:'Bags',
    description:
      "Inspired by candy paper, the Karla shoulder bag is made of leather and has a golden chain strap that attaches to a metal ring that shrinks the ends of the bag. The bag closes with a zipper and there is one zipper pocket on the inside.",
  },
  {
    id: "4",
    name: "Tower Poppy Bag",
    price: "100€",
    image: "./images/Tower Poppy Bag.png",
    customerName:'David',
    phone:'0449351234',
    email:'David@gmail.com',
    category:'Bags',
    description:
      "The black Torna bag has one white poppy-patterned flower and is made of thick cotton awnings. The bag has two carrying handles and one pocket inside. The material is printed in Helsinki. The poppy was born in 1964, at a time when flowers did not belong to Marimekko's pattern world. Maija Isola wanted to create something new and interesting about this theme, and designed a whole series of strong floral patterns. The iconic flower represents creativity and courage. Marimekko Kioski adds a new, modern dimension to the pattern.",
  },
  {
    id: "5",
    name: "Fabric forest beanie",
    price: "50€",
    image: "./images/Fabric forest beanie.png",
    customerName:'Royce',
    phone:'0449356789',
    email:'Royce@gmail.com',
    category:'Clothing',
    description:
      "Kangasmetsä beanie is made of a soft wool-alpaca blend. The beanie has a warm double-folded edge and a Marimekko patch on the back.",
  },
  {
    id: "6",
    name: "Bowl 5 Dl",
    price: "25€",
    image: "./images/Bowl 5 Dl.png",
    customerName:'Jack',
    phone:'0449377789',
    email:'Jack@gmail.com',
    category:'Home accessories',
    description:
      "The Oval serving bowl is made of brown ceramic, which is machine washable, oven, microwave and freezer resistant. The bowl has a vibrant red glaze that is unique to each piece. Please remove the product label on the bottom of the containers before use. The sticker contains metal.",
  },
  {
    id: "7",
    name: "Plywood Tray 31 Cm",
    price: "30€",
    image: "./images/Plywood Tray 31 Cm.png",
    customerName:'Jack',
    phone:'0449377789',
    email:'Jack@gmail.com',
    category:'Home accessories',
    description:
      "The light tray made of birch plywood has a Suur Unikko pattern. We recommend wiping with a damp cloth or hand washing to clean the tray. Do not soak.",
  },
  {
    id: "8",
    name: "Background Poppy Sweater",
    price: "120€",
    image: "./images/Background Poppy Sweater.png",
    customerName:'Jill',
    phone:'0448777789',
    email:'Jill@gmail.com',
    category:'Clothing',
    description:
      "The back-knit vest is woven from wool and has a poppy pattern. The vest has a polo collar and side slits. The hem has elastic and is longer at the back than at the front. The poppy was born in 1964, at a time when flowers did not belong to Marimekko's pattern world. Maija Isola wanted to create something new and interesting about this theme, and designed a whole series of strong floral patterns.",
  },
  {
    id: "9",
    name: "Light Ankle Boots",
    price: "350€",
    image: "./images/Light Ankle Boots.png",
    customerName:'Jill',
    phone:'0448777789',
    email:'Jill@gmail.com',
    category:'Others',
    description:
      "Lightweight Ankle Boots are made from leather. The shoes have 4 cm high heels and back zippers. The ankle boots have a leather lining and leather soles.",
  },
  {
    id: "10",
    name: "Poppy Mini Manual Umbrella",
    price: "40€",
    image: "./images/Poppy Mini Manual Umbrella.png",
    customerName:'Jerry',
    phone:'0448666689',
    email:'Jerry@gmail.com',
    category:'Others',
    description:
      "This very light and handy sized umbrella fits in any bag. The umbrella is decorated with a Unikko pattern, it has a manual telescopic arm. Symbolizing creativity and courage, Unikko was born at a time when there were hardly any flowers in Marimekko's pattern world. However, Maija Isola was interested in the floral theme, and she decided to design a whole series of new types of strong floral patterns.",
  },
  {
    id: "11",
    name: "Small Purse mini Poppy",
    price: "20€",
    image: "./images/Small Purse mini Poppy.png",
    customerName:'Jerry',
    phone:'0448666689',
    email:'Jerry@gmail.com',
    category:'Bags',
    description:
      "The Small Purse made of cotton is a multi-purpose classic where you can store coins and much more, for example. The purse has a metal frame that is easy to click open and close. The Little Poppy pattern on the purse is printed in Helsinki. The poppy was born in 1964, at a time when flowers did not belong to Marimekko's pattern world. Maija Isola wanted to create something new and interesting about this theme, and designed a whole series of strong floral patterns.",
  },
  {
    id: "12",
    name: "Jacket",
    price: "305€",
    image: "./images/Jacket.png",
    customerName:'Jeny',
    phone:'0434566689',
    email:'Jeny@gmail.com',
    category:'Clothing',
    description:
      "The poppy-patterned Harjumetsä lightweight padded jacket has a high collar, a two-way zipper and a push-button fastening at the front. There are strip pockets on the front with zippers. The hem has drawstrings and the sleeves have knitted cuffs. The main material of the product is made of 100% recycled polyester. The poppy was born in 1964, at a time when flowers did not belong to Marimekko's pattern world. Maija Isola wanted to create something new and interesting about this theme, and designed a whole series of strong floral patterns.",
  },
  {
    id: "13",
    name: "Vinde Poppy Placement",
    price: "45€",
    image: "./images/Vinde Poppy Placement.png",
    customerName:'Joyce',
    phone:'0467866689',
    email:'Joyce@gmail.com',
    category:'Clothing',
    description:
      "Pattern: Poppy, Pattern designer: Maija and Kristina Isola, Color: l.white, l.green, v.blue, Country of manufacture: Portugal, Article number: 090101, Color number: 661",
  },
  {
    id: "14",
    name: "Flower vase",
    price: "45€",
    image: "./images/Flower vase.png",
    customerName:'Sonnet',
    phone:'0435866689',
    email:'Sonnet@gmail.com',
    category:'Home accessories',
    description:
      "The small Flower Vase is designed and made of mouth-blown glass by Carina Seth Andersson. We recommend hand washing the vase.",
  },
  {
    id: "15",
    name: "Cushion Cover 50x50 Cm",
    price: "400€",
    image: "./images/Cushion Cover 50x50 Cm.png",
    customerName:'Joyce',
    phone:'0467866689',
    email:'Joyce@gmail.com',
    category:'Home accessories',
    description:
      "The pillowcase made of cotton has a pattern of Suur Unikko. The poppy was born in 1964, at a time when flowers did not belong to Marimekko's pattern world. Maija Isola wanted to create something new and interesting about this theme, and designed a whole series of strong floral patterns.",
  },
  {
    id: "16",
    name: "Candlestick",
    price: "60€",
    image: "./images/Candlestick.png",
    customerName:'Harry',
    phone:'0467855589',
    email:'Harry@gmail.com',
    category:'Home accessories',
    description:
      "The Puteli candlestick is designed by Carina Seth Andersson and is made of mouth-blown glass. The metal candle holder must be removed. We recommend washing the product by hand.",
  },
  {
    id: "17",
    name: "Sneakers",
    price: "135€",
    image: "./images/Sneakers.png",
    customerName:'Mike',
    phone:'0467677789',
    email:'Mike@gmail.com',
    category:'Others',
    description:
      "The Drutha sneakers are made of Mini Unikko-patterned cotton awnings printed in Helsinki. The shoes have 3 cm thick rubber soles with Marimekko logos on the bottom. The rubber soles are made of recycled rubber. The poppy was born in 1964, at a time when flowers did not belong to Marimekko's pattern world. Maija Isola wanted to create something new and interesting about this theme, and designed a whole series of strong floral patterns.",
  },
  {
    id: "18",
    name: "Hat",
    price: "105€",
    image: "./images/Hat.png",
    customerName:'Mike',
    phone:'0467677789',
    email:'Mike@gmail.com',
    category:'Clothing',
    description:
      "The reversible Hilleri cylinder hat is made of cotton awning printed in Helsinki. The hat has a quilted cylinder and the Marimekko logo. On the right side of the hat is the Little Seagull pattern and on the back is the Little Poppy pattern. S = 56 cm M = 58 cm L = 60 cm In honor of our 70th anniversary, we have invited interesting designers to interpret Marimekko's design philosophy in their own style. The result is Marimekko Co-created. The third collection of the year was created in collaboration with Japanese fashion designer Wataru Tominaga. The idea for the Lokki model was born when Maija Isola was looking at a small window with a curtain drawn in front of it. The sun was shining, and wavy shadows formed in the curtain on the wide folds. Maija had an aha experience: if the waves are pressed into the fabric, even a little fabric will look rich and wrinkled. The poppy was born in 1964, at a time when flowers did not belong to Marimekko's pattern world. Maija Isola wanted to create something new and interesting about this theme, and designed a whole series of strong floral patterns.",
  },
  {
    id: "19",
    name: "Polo Shirt",
    price: "150€",
    image: "./images/Polo Shirt.png",
    customerName:'Clint',
    phone:'0467677474',
    email:'clint@gmail.com',
    category:'Clothing',
    description:
      "The body-hugging Puut polo shirt is made of Kottarainen patterned viscose jersey. The shirt has a middle back seam. Kottarainen is a good example of the print patterns designed by Katsuji Wakisaka for Marimekko, which are characterized by free and playful pattern processing.",
  },
  {
    id: "20",
    name: "Scarf",
    price: "155€",
    image: "./images/Scarf.png",
    customerName:'Clint',
    phone:'0467677474',
    email:'clint@gmail.com',
    category:'Clothing',
    description:
      "The Romantica scarf with a large poppy pattern is woven from a wool blend with glittering gold thread. The long scarf has end cases. The poppy was born in 1964, at a time when flowers did not belong to Marimekko's pattern world. Maija Isola wanted to create something new and interesting about this theme, and designed a whole series of strong floral patterns.",
  },
  {
    id: "21",
    name: "Pants",
    price: "155€",
    image: "./images/Pants.png",
    customerName:'Veronica',
    phone:'0467686867',
    email:'Veronica@gmail.com',
    category:'Clothing',
    description:
      "The Tirsat college pants are made from a lightweight cotton college. The trousers have a wide elastic band and drawstrings at the waist. There is one seat pocket on the back and sloping pockets on the front. The leg openings have elastic and a velvety poppy flower printed on the other front pocket. The garment is unisex in design and size. The poppy was born in 1964, at a time when flowers did not belong to Marimekko's pattern world. Maija Isola wanted to create something new and interesting about this theme, and designed a whole series of strong floral patterns.",
  },
  {
    id: "22",
    name: "Bag",
    price: "80€",
    image: "./images/Bag.png",
    customerName:'Vikky',
    phone:'0467678967',
    email:'Vikky@gmail.com',
    category:'Bags',
    description:
      "The Seidi bag has a Little Poppy pattern. The bag has two sturdy carrying handles and one pocket inside. The thick awning fabric is printed in Helsinki. The poppy was born in 1964, at a time when flowers did not belong to Marimekko's pattern world. Maija Isola wanted to create something new and interesting about this theme, and designed a whole series of strong floral patterns.",
  },
  {
    id: "23",
    name: "Duvet Cover 240x220cm",
    price: "95€",
    image: "./images/Duvet Cover 240x220cm.png",
    customerName:'Vikky',
    phone:'0467678967',
    email:'Vikky@gmail.com',
    category:'Home accessories',
    description:
      "The double-sided duvet cover made of cotton has a Lokki pattern. The duvet cover has a thread count of TC 200 and has corner openings at the top to make it easier to change sheets. The idea for the Lokki model was born when Maija Isola was looking at a small window with a curtain drawn in front of it. The sun was shining, and wavy shadows formed in the curtain on the wide folds. Maija had an aha experience: if the waves are pressed into the fabric, even a little fabric will look rich and wrinkled.",
  },
  {
    id: "24",
    name: "Skirt",
    price: "220€",
    image: "./images/Skirt.png",
    customerName:'Monika',
    phone:'0467677766',
    email:'Monika@gmail.com',
    category:'Clothing',
    description:
      "The soft Poikue skirt is made of boiled wool. The A-line skirt has an elastic waist and a hem at the hem.",
  },
];
