export const items = [
  {
    id: "1",
    name: "Coffee Cup 2dl",
    price: "8€",
    image: "/images/Coffee Cup 2dl.png",
  },
  {
    id: "2",
    name: "Plate 15x12cm",
    price: "30€",
    image: "./images/Plate 15x12cm.png",
  },
  {
    id: "3",
    name: "Karla Chain Bag",
    price: "220€",
    image: "./images/Karla Chain Bag.png",
  },
  {
    id: "4",
    name: "Tower Poppy Bag",
    price: "100€",
    image: "./images/Tower Poppy Bag.png",
  },
  {
    id: "5",
    name: "Fabric forest beanie",
    price: "50€",
    image: "./images/Fabric forest beanie.png",
  },
  { id: "6", name: "Bowl 5 Dl", price: "25€", image: "./images/Bowl 5 Dl.png" },
  {
    id: "7",
    name: "Plywood Tray 31 Cm",
    price: "30€",
    image: "./images/Plywood Tray 31 Cm.png",
  },
  {
    id: "8",
    name: "Background Poppy Sweater",
    price: "120€",
    image: "./images/Background Poppy Sweater.png",
  },
  {
    id: "9",
    name: "Light Ankle Boots",
    price: "350€",
    image: "./images/Light Ankle Boots.png",
  },
  {
    id: "10",
    name: "Poppy Mini Manual Umbrella",
    price: "40€",
    image: "./images/Poppy Mini Manual Umbrella.png",
  },
  {
    id: "11",
    name: "Small Purse mini Poppy",
    price: "20€",
    image: "./images/Small Purse mini Poppy.png",
  },
  {
    id: "12",
    name: "Jacket",
    price: "305€",
    image: "./images/Jacket.png",
  },
  {
    id: "13",
    name: "Vinde Poppy Placement",
    price: "45€",
    image: "./images/Vinde Poppy Placement.png",
  },
  {
    id: "14",
    name: "Flower vase",
    price: "45€",
    image: "./images/Flower vase.png",
  },
  {
    id: "15",
    name: "Cushion Cover 50x50 Cm",
    price: "400€",
    image: "./images/Cushion Cover 50x50 Cm.png",
  },
  {
    id: "16",
    name: "Candlestick",
    price: "60€",
    image: "./images/Candlestick.png",
  },
  {
    id: "17",
    name: "Sneakers",
    price: "135€",
    image: "./images/Sneakers.png",
  },
  {
    id: "18",
    name: "Hat",
    price: "105€",
    image: "./images/Hat.png",
  },
  {
    id: "19",
    name: "Polo Shirt",
    price: "150€",
    image: "./images/Polo Shirt.png",
  },
  {
    id: "20",
    name: "Scarf",
    price: "155€",
    image: "./images/Scarf.png",
  },
  {
    id: "21",
    name: "Pants",
    price: "155€",
    image: "./images/Pants.png",
  },
  {
    id: "22",
    name: "Bag",
    price: "80€",
    image: "./images/Bag.png",
  },
  {
    id: "23",
    name: "Duvet Cover 240x220cm",
    price: "95€",
    image: "./images/Duvet Cover 240x220cm.png",
  },
  {
    id: "24",
    name: "Skirt",
    price: "220€",
    image: "./images/Skirt.png",
  },
];
