export const items = [
  { id: "1", name: "shoes", price: "150€" },
  { id: "2", name: "tshirt", price: "100€" },
  { id: "3", name: "jeans", price: "70€" },
  { id: "4", name: "bags", price: "100€" },
  { id: "5", name: "sneaker", price: "50€" },
  { id: "6", name: "hat", price: "50€" },
  { id: "7", name: "footwear", price: "150€" },
  { id: "8", name: "gown", price: "250€" },
  { id: "9", name: "shirt", price: "50€" },
  { id: "10", name: "swimwear", price: "150€" },
  { id: "11", name: "scarf", price: "30€" },
  { id: "12", name: "ring", price: "350€" },
  { id: "13", name: "earings", price: "450€" },
  { id: "14", name: "watch", price: "550€" },
  { id: "15", name: "necklace", price: "400€" },
  { id: "16", name: "bangles", price: "200€" },
  { id: "17", name: "curtain", price: "75€" },
  { id: "18", name: "kurta", price: "60€" },
  { id: "19", name: "mat", price: "40€" },
  { id: "20", name: "bedsheet", price: "220€" },
  { id: "21", name: "chair", price: "150€" },
  { id: "22", name: "table", price: "450€" },
  { id: "23", name: "lamp", price: "80€" },
  { id: "24", name: "teddy-bear", price: "30€" },
];
